/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.matrizb2;

import java.util.Random;
import javax.swing.DefaultListModel;
/**
 *
 * @author willr
 */
public class MatrizB2 extends javax.swing.JFrame {
int matriz [][] = new int [10][5];
DefaultListModel lstValores;

    /**
     * Creates new form MatrizB2
     */
    public MatrizB2() {
        lstValores = new DefaultListModel(); 
         initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botger = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listabusca1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        visorresult = new javax.swing.JTextArea();
        TIPORESULTADO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botger.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botger.setText("GERAR MATRIZ");
        botger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botgerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("BUSCAR VALOR:");

        valor.setEnabled(false);
        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbuscar.setText("BUSCAR!!");
        btnbuscar.setEnabled(false);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("BUSCAS");

        listabusca1.setBorder(new javax.swing.border.MatteBorder(null));
        listabusca1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listabusca1.setModel(lstValores);
        jScrollPane1.setViewportView(listabusca1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("RESULTADO");

        visorresult.setColumns(20);
        visorresult.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        visorresult.setRows(5);
        jScrollPane2.setViewportView(visorresult);

        TIPORESULTADO.setEditable(false);
        TIPORESULTADO.setBackground(java.awt.SystemColor.control);
        TIPORESULTADO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TIPORESULTADO.setForeground(new java.awt.Color(255, 51, 51));
        TIPORESULTADO.setBorder(null);
        TIPORESULTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIPORESULTADOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TIPORESULTADO))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botger, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(botger, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnbuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(TIPORESULTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void botgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botgerActionPerformed
 btnbuscar.setEnabled(true);
 valor.setEnabled(true);
        Random aleatorio=new Random();
    for(int linha=0;linha<10;linha++){
        for(int coluna=0;coluna<5;coluna++){
            matriz[linha][coluna]= aleatorio.nextInt(100);
            System.out.print(matriz[linha][coluna]+"\t");
            //System.out.println("COLUNA=" +coluna);
        }
        //System.out.println("LINHA=" +linha);
        System.out.print("\n"); 
    }
    botger.setEnabled(false);
    }//GEN-LAST:event_botgerActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
visorresult.setText(null);
lstValores.addElement(valor.getText());
int vM = 0;
int vU = (Integer.parseInt(valor.getText()));
int Min = vU -2;
int Max = vU +2;
int existe = 0;
String tela = valor.getText();
        for(int linha = 0; linha < 10 ; linha++){  
            for(int coluna = 0; coluna < 5 ; coluna++){ 
                vM = matriz[linha][coluna];
                if ( vM == vU){
                    TIPORESULTADO.setText("EXATO");
                    visorresult.append("\nNumero: "+vU+" na posição: C["+coluna+"]L["+linha+"]\n");
                    System.out.println("Posicao:C["+coluna+"]L["+linha+"]="+vU);
                    existe = 1;
                }
            }    
        }
 if (existe == 0){
            for(int linha = 0; linha < 10 ; linha++){  
                for(int coluna = 0; coluna < 5 ; coluna++){ 
                    vM = matriz[linha][coluna]++;        
                    if  ( vM >= Min && vM <= Max ){
                        TIPORESULTADO.setText("APROXIMADO");
                        visorresult.append("\nNumero: "+vM+" na posição C["+coluna+"]L["+linha+"]="+vM+"\n");
                        System.out.println("Posicao:C["+coluna+"]L["+linha+"]="+vM);
                        existe = 1;
                    }
                }   
            }
        }
 if (existe == 0){
            if ( vM < Min || vM > Max ){
               TIPORESULTADO.setText("NÃO ENCONTRADO!"); 
               visorresult.append("\nNumero "+vU+" não encontrado!\n");
                existe = 1;
            }}
 visorresult.append("------------------------------------------");
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed

    private void TIPORESULTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIPORESULTADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIPORESULTADOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatrizB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatrizB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatrizB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatrizB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatrizB2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TIPORESULTADO;
    private javax.swing.JButton botger;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listabusca1;
    private javax.swing.JTextField valor;
    private javax.swing.JTextArea visorresult;
    // End of variables declaration//GEN-END:variables
}
